# fly.toml app configuration file generated for snews on 2024-05-27T22:45:16-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snews'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
