CREATE TABLE NEWSLETTER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    SUBJECT TEXT NOT NULL,
    CONTENT_ATTACHMENT_PATH TEXT NOT NULL
);

CREATE TABLE RECEIPIENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL TEXT NOT NULL,
    NEWSLETTER_ID INTEGER NOT NULL,

    FOREIGN KEY (NEWSLETTER_ID)
      REFERENCES NEWSLETTER(ID)
);

INSERT INTO NEWSLETTER (NAME, DESCRIPTION, SUBJECT, CONTENT_ATTACHMENT_PATH)
VALUES ('NEWSLETTER 1', 'DESCRIPTION 1', 'SUBJECT 1', 'PATH/TO/CONTENT1');
